<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="catalogue.xsl" type="text/xsl" ?>

<!DOCTYPE CATALOGUE [
<!ELEMENT CATALOGUE (LEASH*)>
<!ELEMENT LEASH (TITLE,PRICE,MAT,DESC)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT PRICE (#PCDATA)>
<!ELEMENT MAT (#PCDATA)>
<!ELEMENT DESC (#PCDATA)>
<!ELEMENT IMG (#PCDATA)>
]>

<CATALOGUE> 							
	<LEASH> 		
		<TITLE>Blue Wave</TITLE>
		<PRICE>$13.99</PRICE> 
		<MAT>Latex</MAT>			
		<DESC>Words</DESC>
		<IMG>../images/fishimages/clownfish.jpg</IMG>
	</LEASH>
	<LEASH> 		
		<TITLE>Blue Wave</TITLE>
		<PRICE>$13.99</PRICE> 
		<MAT>Latex</MAT>			
		<DESC>Words</DESC>
		<IMG>../images/fishimages/clownfish.jpg</IMG>
	</LEASH>
	<LEASH> 		
		<TITLE>Blue Wave</TITLE>
		<PRICE>$13.99</PRICE> 
		<MAT>Latex</MAT>			
		<DESC>Words</DESC>
		<IMG>../images/fishimages/clownfish.jpg</IMG>
	</LEASH>
	<LEASH> 		
		<TITLE>Blue Wave</TITLE>
		<PRICE>$13.99</PRICE> 
		<MAT>Latex</MAT>			
		<DESC>Words</DESC>
		<IMG>../images/fishimages/clownfish.jpg</IMG>
	</LEASH>
	<LEASH> 		
		<TITLE>Blue Wave</TITLE>
		<PRICE>$13.99</PRICE> 
		<MAT>Latex</MAT>			
		<DESC>Words</DESC>
		<IMG>../images/fishimages/clownfish.jpg</IMG>
	</LEASH>
	<LEASH> 		
		<TITLE>Blue Wave</TITLE>
		<PRICE>$13.99</PRICE> 
		<MAT>Latex</MAT>			
		<DESC>Words</DESC>
		<IMG>../images/fishimages/clownfish.jpg</IMG>
	</LEASH>
	<LEASH> 		
		<TITLE>Blue Wave</TITLE>
		<PRICE>$13.99</PRICE> 
		<MAT>Latex</MAT>			
		<DESC>Words</DESC>
		<IMG>../images/fishimages/clownfish.jpg</IMG>
	</LEASH>
	<LEASH> 		
		<TITLE>Blue Wave</TITLE>
		<PRICE>$13.99</PRICE> 
		<MAT>Latex</MAT>			
		<DESC>Words</DESC>
		<IMG>../images/fishimages/clownfish.jpg</IMG>
	</LEASH>
	<LEASH> 		
		<TITLE>Blue Wave</TITLE>
		<PRICE>$13.99</PRICE> 
		<MAT>Latex</MAT>			
		<DESC>Words</DESC>
		<IMG>../images/fishimages/clownfish.jpg</IMG>
	</LEASH>
	<LEASH> 		
		<TITLE>Blue Wave</TITLE>
		<PRICE>$13.99</PRICE> 
		<MAT>Latex</MAT>			
		<DESC>Words</DESC>
		<IMG>../images/fishimages/clownfish.jpg</IMG>
	</LEASH>
</CATALOGUE>